name: Deploy Staging to Docker Hub

on:
  push:
    branches:
      - linda_v2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Changed Files
        id: changed-files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            flask:
              - 'TA_201_Flask/**'
              - 'Docker/Dockerfile/flask.Dockerfile'
            app:
              - '!(TA_201_Flask/**|Docker/Dockerfile/flask.Dockerfile)'  # Everything except Flask-related changes

      - name: Build and Push Flask Image (Only if Flask files changed)
        if: steps.changed-files.outputs.flask == 'true'
        run: |
          echo "Detected changes in Flask files. Building Flask image..."
          docker build -f Docker/Dockerfile/flask.Dockerfile -t 3b052lindasantika/assessment-app-kota201-flask .
          docker push 3b052lindasantika/assessment-app-kota201-flask

      - name: Build and Push App Image (If anything except Flask changed)
        if: steps.changed-files.outputs.app == 'true'
        run: |
          echo "Building main application image..."
          docker build -f Docker/Dockerfile/app.Dockerfile -t 3b052lindasantika/assessment-app-kota201 .
          docker push 3b052lindasantika/assessment-app-kota201
